shopt -s expand_aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto --exclude-dir=.git --exclude=*.sw? --exclude=*.pyc'
alias fgrep='fgrep --color=auto --exclude-dir=.git --exclude=*.sw? --exclude=*.pyc'
alias egrep='egrep --color=auto --exclude-dir=.git --exclude=*.sw? --exclude=*.pyc'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias dua='du -sch .[!.]* * | sort -h'
alias decolorize='sed "s/\x1B\[[0-9;]*[JKmsu]//g"'
alias gf='git fetchp'
alias gg='git graph'
alias gp='git pullp'
alias vimclean='find -iname "*.sw?" -delete'
alias cb='cargo build --color always 2>&1 | less -RC'
alias cr='cargo run --color always 2>&1 | less -RC'
alias ct='cargo test --color always -- --nocapture 2>&1 | less -RC'
alias cg='cargo playground --color always 2>&1 | less -RC'
alias cs='cargo sweep --time 1'
alias ce='cargo expand --lib'
alias j='just'
